var x = {
   "CurrentVm":{
      "ParallelsVirtualMachine":{
         "AppVersion":"16.0.0-48916",
         "ValidRc":"0",
         "Identification":{
            "VmUuid":"{ec6f7b74-35fe-47af-9ea7-109ffab00289}",
            "SourceVmUuid":"{ec6f7b74-35fe-47af-9ea7-109ffab00289}",
            "LinkedVmUuid":"",
            "LinkedSnapshotUuid":"",
            "VmName":"ITDATA-vm2",
            "ServerUuid":"{46f8433f-ad4c-4aa1-98cc-c2248ebd6df1}",
            "ServerUuidAs":"",
            "LastServerUuid":"",
            "ServerHost":"",
            "VmHome":"/Users/tedinger/Parallels/ITDATA-vm2.pvm/config.pvs",
            "VmFilesLocation":"1",
            "VmLocationName":"Macintosh HD",
            "VmCreationDate":"2019-03-11 23:37:35",
            "VmUptimeStartDateTime":"2019-03-11 23:37:35",
            "VmUptimeInSeconds":"21879303",
            "_dyn_lists":""
         },
         "Security":{
            "AccessControlList":{
               "_dyn_lists":"AccessControl"
            },
            "LockedOperationsList":{
               "_dyn_lists":"LockedOperation"
            },
            "PasswordProtectedOperations":{
               "_dyn_lists":"LockedOperation"
            },
            "LockDownHash":"",
            "LockDownRuntime":{
               "CustomAuthorized":"0",
               "_dyn_lists":""
            },
            "Owner":"",
            "IsOwner":"0",
            "AccessForOthers":"0",
            "LockedSign":"0",
            "PermissionsRuntime":{
               "DevicesPermissionsRuntime":{
                  "_dyn_lists":"DevicePrivacyRestriction 0"
               },
               "_dyn_lists":""
            },
            "_dyn_lists":""
         },
         "Settings":{
            "General":{
               "OsType":"8",
               "OsNumber":"2063",
               "VmDescription":"",
               "IsTemplate":"0",
               "CustomProperty":"",
               "SwapDir":"",
               "VmColor":"0",
               "Profile":{
                  "Type":"2",
                  "Custom":"0",
                  "_Custom_patch":"1",
                  "_dyn_lists":""
               },
               "AssetId":"",
               "SerialNumber":"",
               "_dyn_lists":"PrevOsNumber"
            },
            "Startup":{
               "AutoStart":"0",
               "AutoStartDelay":"0",
               "VmStartLoginMode":"0",
               "VmStartAsUser":"",
               "VmStartAsPassword":"",
               "WindowMode":"0",
               "StartInDetachedWindow":"0",
               "BootingOrder":{
                  "BootDevice":[
                     {
                        "Index":"1",
                        "Type":"8",
                        "BootingNumber":"4",
                        "InUse":"1",
                        "_id":"31",
                        "_dyn_lists":""
                     },
                     {
                        "Index":"0",
                        "Type":"6",
                        "BootingNumber":"0",
                        "InUse":"1",
                        "_id":"32",
                        "_dyn_lists":""
                     },
                     {
                        "Index":"0",
                        "Type":"15",
                        "BootingNumber":"2",
                        "InUse":"0",
                        "_id":"33",
                        "_dyn_lists":""
                     },
                     {
                        "Index":"0",
                        "Type":"5",
                        "BootingNumber":"1",
                        "InUse":"1",
                        "_id":"34",
                        "_dyn_lists":""
                     },
                     {
                        "Index":"0",
                        "Type":"8",
                        "BootingNumber":"3",
                        "InUse":"0",
                        "_id":"35",
                        "_dyn_lists":""
                     }
                  ],
                  "_dyn_lists":"BootDevice 36"
               },
               "AllowSelectBootDevice":"0",
               "Bios":{
                  "EfiEnabled":"0",
                  "EfiSecureBoot":"0",
                  "_dyn_lists":""
               },
               "ExternalDeviceSystemName":"",
               "RecoveryVolumeSystemName":"",
               "_AutoStart_patch":"2",
               "_dyn_lists":""
            },
            "Shutdown":{
               "AutoStop":"1",
               "OnVmWindowClose":"1",
               "WindowOnShutdown":"0",
               "ReclaimDiskSpace":"0",
               "_OnVmWindowClose_patch":"1",
               "_dyn_lists":""
            },
            "SasProfile":{
               "Custom":"1",
               "_dyn_lists":""
            },
            "Runtime":{
               "ForegroundPriority":"1",
               "BackgroundPriority":"1",
               "DiskCachePolicy":"1",
               "CloseAppOnShutdown":"0",
               "ActionOnStop":"0",
               "DockIcon":"0",
               "OsResolutionInFullScreen":"0",
               "FullScreen":{
                  "UseAllDisplays":"1",
                  "UseActiveCorners":"0",
                  "UseNativeFullScreen":"1",
                  "CornerAction":[
                     "1",
                     "0",
                     "0",
                     "0"
                  ],
                  "ScaleViewMode":"1",
                  "EnableGammaControl":"1",
                  "OptimiseForGames":"0",
                  "ActivateSpacesOnClick":"0",
                  "_CornerAction_patch":"2",
                  "_dyn_lists":"CornerAction"
               },
               "UndoDisks":"0",
               "SafeMode":"0",
               "SystemFlags":"",
               "DisableAPIC":"0",
               "OptimizePowerConsumptionMode":"1",
               "ShowBatteryStatus":"1",
               "Enabled":"0",
               "EnableAdaptiveHypervisor":"1",
               "UseSMBiosData":"0",
               "DisableSpeaker":"1",
               "HideBiosOnStartEnabled":"0",
               "UseDefaultAnswers":"0",
               "CompactHddMask":"0",
               "CompactMode":"0",
               "DisableWin7Logo":"1",
               "OptimizeModifiers":"3",
               "StickyMouse":"0",
               "PauseOnDeactivation":"0",
               "FEATURES_MASK":"0",
               "EXT_FEATURES_MASK":"0",
               "EXT_80000001_ECX_MASK":"0",
               "EXT_80000001_EDX_MASK":"0",
               "EXT_80000007_EDX_MASK":"0",
               "EXT_80000008_EAX":"0",
               "EXT_00000007_EBX_MASK":"0",
               "EXT_00000007_EDX_MASK":"0",
               "EXT_0000000D_EAX_MASK":"0",
               "EXT_00000006_EAX_MASK":"0",
               "CpuFeaturesMaskValid":"0",
               "InternalVmInfo":{
                  "ParallelsEvent":{
                     "EventType":"100000",
                     "EventLevel":"0",
                     "EventCode":"0",
                     "EventNeedResponse":"0",
                     "EventIssuerType":"0",
                     "EventIssuerId":"{b80b3f0a-8908-4d56-9b97-3593990a43c0}",
                     "EventSource":"",
                     "EventInitialRequestId":"{d81218aa-5100-475e-9932-c54dcc3e0430}",
                     "EventParameters":{
                        "_dyn_lists":"EventParameter 0"
                     },
                     "EventId":"0",
                     "_dyn_lists":""
                  },
                  "_dyn_lists":""
               },
               "UnattendedInstallLocale":"",
               "UnattendedInstallEdition":"",
               "UnattendedEvaluationVersion":"0",
               "HostRetinaEnabled":"1",
               "DebugServer":{
                  "Port":"0",
                  "State":"0",
                  "_dyn_lists":""
               },
               "HypervisorType":"0",
               "ResourceQuota":"100",
               "_UndoDisks_patch":"1",
               "_OptimizePowerConsumptionMode_patch":"1",
               "_StickyMouse_patch":"2",
               "_CompactMode_patch":"1",
               "_dyn_lists":""
            },
            "Schedule":{
               "SchedBasis":"0",
               "SchedGranularity":"0",
               "SchedDayOfWeek":"0",
               "SchedDayOfMonth":"0",
               "SchedDay":"0",
               "SchedWeek":"0",
               "SchedMonth":"0",
               "SchedStartDate":"1752-01-01",
               "SchedStartTime":"",
               "SchedStopDate":"1752-01-01",
               "SchedStopTime":"",
               "_dyn_lists":""
            },
            "RemoteDisplay":{
               "Mode":"0",
               "Password":"",
               "HostName":"0.0.0.0",
               "PortNumber":"0",
               "Encrypted":"0",
               "_dyn_lists":""
            },
            "Tools":{
               "ToolsVersion":"16.0.0-48916",
               "IsolatedVm":"0",
               "NonAdminToolsUpgrade":"1",
               "LockGuestOnSuspend":"0",
               "SyncVmHostname":"0",
               "SyncSshIds":"0",
               "Coherence":{
                  "ShowTaskBar":"1",
                  "ShowTaskBarInCoherence":"0",
                  "RelocateTaskBar":"0",
                  "ExcludeDock":"1",
                  "MultiDisplay":"1",
                  "GroupAllWindows":"0",
                  "DisableDropShadow":"0",
                  "DoNotMinimizeToDock":"0",
                  "BringToFront":"0",
                  "AppInDock":"0",
                  "ShowWinSystrayInMacMenu":"0",
                  "UseBorders":"0",
                  "UseSeamlessMode":"1",
                  "SwitchToFullscreenOnDemand":"0",
                  "PauseIdleVM":"0",
                  "PauseIdleVMTimeout":"30",
                  "DisableAero":"0",
                  "CoherenceButtonVisibility":"1",
                  "AlwaysOnTop":"0",
                  "WindowAnimation":"1",
                  "_GroupAllWindows_patch":"1",
                  "_MultiDisplay_patch":"1",
                  "_BringToFront_patch":"1",
                  "_ShowTaskBar_patch":"1",
                  "_DoNotMinimizeToDock_patch":"1",
                  "_AlwaysOnTop_patch":"1",
                  "_RelocateTaskBar_patch":"1",
                  "_ExcludeDock_patch":"1",
                  "_dyn_lists":""
               },
               "SharedFolders":{
                  "HostSharing":{
                     "Enabled":"1",
                     "ShareAllMacDisks":"1",
                     "ShareUserHomeDir":"0",
                     "MapSharedFoldersOnLetters":"1",
                     "UserDefinedFoldersEnabled":"1",
                     "SetExecBitForFiles":"0",
                     "VirtualLinks":"1",
                     "EnableDos8dot3Names":"1",
                     "SharedShortcuts":"1",
                     "SharedCloud":"0",
                     "_MapSharedFoldersOnLetters_patch":"1",
                     "_dyn_lists":"SharedFolder 0"
                  },
                  "GuestSharing":{
                     "Enabled":"1",
                     "AutoMount":"1",
                     "AutoMountNetworkDrives":"1",
                     "EnableSpotlight":"0",
                     "AutoMountCloudDrives":"1",
                     "ShareRemovableDrives":"1",
                     "PortNumber":"0",
                     "AllowExec":"0",
                     "_ShareRemovableDrives_patch":"1",
                     "_dyn_lists":""
                  },
                  "_dyn_lists":""
               },
               "SharedProfile":{
                  "Enabled":"0",
                  "UseDesktop":"1",
                  "UseDocuments":"1",
                  "UsePictures":"1",
                  "UseMusic":"1",
                  "UseMovies":"1",
                  "UseDownloads":"1",
                  "UseTrashBin":"1",
                  "_dyn_lists":""
               },
               "SharedApplications":{
                  "FromWinToMac":"1",
                  "FromMacToWin":"0",
                  "SmartSelect":"1",
                  "AppInDock":"1",
                  "ShowWindowsAppInDock":"0",
                  "ShowGuestNotifications":"1",
                  "BounceDockIconWhenAppFlashes":"1",
                  "WebApplications":{
                     "WebBrowser":"0",
                     "EmailClient":"0",
                     "FtpClient":"0",
                     "Newsgroups":"0",
                     "Rss":"0",
                     "RemoteAccess":"0",
                     "_dyn_lists":""
                  },
                  "IconGroupingEnabled":"1",
                  "AddInstalledApplicationsToLaunchpad":"0",
                  "DisableRecentDocs":"0",
                  "StoreInternetPasswordsInOSXKeychain":"0",
                  "_dyn_lists":""
               },
               "AutoUpdate":{
                  "Enabled":"1",
                  "_dyn_lists":""
               },
               "ClipboardSync":{
                  "Enabled":"1",
                  "PreserveTextFormatting":"1",
                  "_Enabled_patch":"1",
                  "_dyn_lists":""
               },
               "DragAndDrop":{
                  "Enabled":"1",
                  "_Enabled_patch":"1",
                  "_dyn_lists":""
               },
               "KeyboardLayoutSync":{
                  "Enabled":"1",
                  "_dyn_lists":""
               },
               "MouseSync":{
                  "Enabled":"1",
                  "_dyn_lists":""
               },
               "MouseVtdSync":{
                  "Enabled":"1",
                  "_dyn_lists":""
               },
               "SmartMouse":{
                  "Enabled":"0",
                  "_dyn_lists":""
               },
               "SmoothScrolling":{
                  "Enabled":"1",
                  "_dyn_lists":""
               },
               "TimeSync":{
                  "Enabled":"1",
                  "SyncInterval":"60",
                  "KeepTimeDiff":"0",
                  "SyncHostToGuest":"0",
                  "SyncTimezoneDisabled":"0",
                  "_SyncInterval_patch":"1",
                  "_dyn_lists":""
               },
               "TisDatabase":{
                  "Data":"",
                  "_dyn_lists":""
               },
               "Modality":{
                  "Opacity":"0.5",
                  "StayOnTop":"1",
                  "CaptureMouseClicks":"1",
                  "UseWhenAppInBackground":"1",
                  "ShowOnAllSpaces":"1",
                  "_Opacity_patch":"",
                  "_StayOnTop_patch":"",
                  "_dyn_lists":""
               },
               "SharedVolumes":{
                  "Enabled":"1",
                  "UseExternalDisks":"1",
                  "UseDVDs":"1",
                  "UseConnectedServers":"1",
                  "UseInversedDisks":"0",
                  "_dyn_lists":""
               },
               "Gestures":{
                  "Enabled":"1",
                  "OneFingerSwipe":"0",
                  "_Enabled_patch":"1",
                  "_dyn_lists":""
               },
               "RemoteControl":{
                  "Enabled":"1",
                  "_dyn_lists":""
               },
               "LocationProvider":{
                  "Enabled":"1",
                  "_dyn_lists":""
               },
               "AutoSyncOSType":{
                  "Enabled":"1",
                  "_dyn_lists":""
               },
               "WinMaintenance":{
                  "Enabled":"0",
                  "ScheduleDay":"9",
                  "ScheduleTime":"00:00:00",
                  "_dyn_lists":""
               },
               "DevelopOptions":{
                  "ShowInMenu":"1",
                  "_ShowInMenu_patch":"1",
                  "_dyn_lists":""
               },
               "DiskSpaceOptimization":{
                  "SyncFreeSpaceFromHost":"0",
                  "_dyn_lists":""
               },
               "_dyn_lists":""
            },
            "Autoprotect":{
               "Enabled":"0",
               "Period":"86400",
               "TotalSnapshots":"3",
               "Schema":"2",
               "NotifyBeforeCreation":"1",
               "_Period_patch":"1",
               "_dyn_lists":""
            },
            "AutoCompress":{
               "Enabled":"0",
               "Period":"86400",
               "FreeDiskSpaceRatio":"50",
               "_Enabled_patch":"1",
               "_dyn_lists":""
            },
            "GlobalNetwork":{
               "HostName":"",
               "DefaultGateway":"",
               "DefaultGatewayIPv6":"",
               "AutoApplyIpOnly":"0",
               "SubnetIndex":"0",
               "_dyn_lists":"DnsIPAddress SearchDomain"
            },
            "VmEncryptionInfo":{
               "Enabled":"0",
               "PluginId":"",
               "Hash1":"",
               "Hash2":"",
               "_dyn_lists":""
            },
            "VmProtectionInfo":{
               "Enabled":"0",
               "Hash1":"",
               "Hash2":"",
               "Hash3":"",
               "ExpirationInfo":{
                  "Enabled":"0",
                  "ExpirationDate":"1752-01-01 00:00:00",
                  "TrustedTimeServerUrl":"https://parallels.com",
                  "Note":"",
                  "TimeCheckIntervalSeconds":"1800",
                  "OfflineTimeToLiveSeconds":"864000",
                  "_dyn_lists":""
               },
               "_dyn_lists":""
            },
            "SharedCamera":{
               "Enabled":"1",
               "_Enabled_patch":"1",
               "_dyn_lists":""
            },
            "SharedCCID":{
               "Enabled":"0",
               "_Enabled_patch":"",
               "_dyn_lists":""
            },
            "Keyboard":{
               "HardwareLayout":"0",
               "_dyn_lists":""
            },
            "VirtualPrintersInfo":{
               "UseHostPrinters":"1",
               "SyncDefaultPrinter":"1",
               "ShowHostPrinterUI":"1",
               "_ShowHostPrinterUI_patch":"1",
               "_UseHostPrinters_patch":"1",
               "_dyn_lists":""
            },
            "SharedBluetooth":{
               "Enabled":"0",
               "_Enabled_patch":"",
               "_dyn_lists":""
            },
            "LockDown":{
               "Hash":"",
               "_dyn_lists":""
            },
            "UsbController":{
               "UhcEnabled":"1",
               "EhcEnabled":"1",
               "XhcEnabled":"1",
               "ExternalDevices":{
                  "Disks":"1",
                  "HumanInterfaces":"1",
                  "Communication":"1",
                  "Audio":"1",
                  "Video":"1",
                  "SmartCards":"1",
                  "Printers":"1",
                  "SmartPhones":"1",
                  "Other":"1",
                  "_dyn_lists":""
               },
               "_UhcEnabled_patch":"1",
               "_dyn_lists":""
            },
            "OnlineCompact":{
               "Mode":"0",
               "_Mode_patch":"",
               "_dyn_lists":""
            },
            "TravelOptions":{
               "Enabled":"0",
               "Condition":{
                  "Enter":"0",
                  "EnterBetteryThreshold":"30",
                  "Quit":"0",
                  "_dyn_lists":""
               },
               "SavedOptions":{
                  "_dyn_lists":"PauseIdleVM 0 AdaptiveHV 0 OptimizePower 0 AutoprotectOptions 0 NetAdapter 0"
               },
               "_dyn_lists":""
            },
            "ArchivingOptions":{
               "Enabled":"0",
               "_dyn_lists":""
            },
            "PackingOptions":{
               "State":"0",
               "Direction":"0",
               "Progress":"0",
               "_dyn_lists":""
            },
            "_dyn_lists":""
         },
         "Hardware":{
            "Cpu":{
               "Number":"6",
               "Mode":"0",
               "AccelerationLevel":"2",
               "EnableVTxSupport":"1",
               "EnableHotplug":"0",
               "VirtualizedHV":"0",
               "VirtualizePMU":"0",
               "_EnableVTxSupport_patch":"1",
               "_dyn_lists":""
            },
            "Chipset":{
               "Type":"1",
               "Version":"4",
               "_Version_patch":"1",
               "_dyn_lists":""
            },
            "Clock":{
               "TimeShift":"0",
               "_dyn_lists":""
            },
            "Memory":{
               "RAM":"16384",
               "EnableHotplug":"0",
               "HostMemQuotaMin":"128",
               "HostMemQuotaMax":"4294967295",
               "HostMemQuotaPriority":"50",
               "AutoQuota":"1",
               "MaxBalloonSize":"70",
               "ExtendedMemoryLimits":"0",
               "_ExtendedMemoryLimits_patch":"1",
               "_dyn_lists":""
            },
            "Video":{
               "Enabled":"1",
               "Type":"0",
               "VideoMemorySize":"0",
               "FifoSize":"1048576",
               "EnableDirectXShaders":"1",
               "ScreenResolutions":{
                  "Enabled":"0",
                  "_dyn_lists":"ScreenResolution 0 DynamicResolution 0"
               },
               "Enable3DAcceleration":"1",
               "EnableVSync":"1",
               "MaxDisplays":"0",
               "EnableHiResDrawing":"0",
               "UseHiResInGuest":"0",
               "HostScaleFactor":"1",
               "NativeScalingInGuest":"0",
               "ApertureOnlyCapable":"1",
               "_VideoMemorySize_patch":"1",
               "_dyn_lists":""
            },
            "HibernateState":{
               "ConfigDirty":"0",
               "SMapType":"1",
               "ShutdownReason":"0",
               "LongReset":"0",
               "CpuFeatures":{
                  "FEATURES_MASK":"529267711",
                  "EXT_FEATURES_MASK":"4158272003",
                  "EXT_80000001_ECX_MASK":"289",
                  "EXT_80000001_EDX_MASK":"672139264",
                  "EXT_80000007_EDX_MASK":"256",
                  "EXT_80000008_EAX":"12324",
                  "EXT_00000007_EBX_MASK":"10225579",
                  "EXT_00000007_EDX_MASK":"0",
                  "EXT_0000000D_EAX_MASK":"3",
                  "EXT_00000006_EAX_MASK":"85",
                  "CpuFeaturesMaskValid":"1",
                  "_dyn_lists":""
               },
               "_dyn_lists":""
            },
            "VirtIOSerial":{
               "ToolgatePort":"0",
               "LoopbackPort":"0",
               "_dyn_lists":""
            },
            "CdRom":{
               "Index":"0",
               "Enabled":"1",
               "Connected":"0",
               "EmulatedType":"1",
               "SystemName":"/Users/tedinger/Desktop/Win10_1809_English_x64.iso",
               "UserFriendlyName":"/Users/tedinger/Desktop/Win10_1809_English_x64.iso",
               "Remote":"0",
               "InterfaceType":"2",
               "StackIndex":"1",
               "Passthrough":"1",
               "SubType":"0",
               "DeviceDescription":"",
               "_id":"0",
               "_dyn_lists":""
            },
            "Hdd":{
               "Uuid":"{aa4d7d1f-1a6e-483c-8eb4-51cf8d090163}",
               "Index":"0",
               "Enabled":"1",
               "Connected":"1",
               "EmulatedType":"1",
               "SystemName":"/Users/tedinger/Parallels/ITDATA-vm2.pvm/ITDATA-vm2-0.hdd",
               "UserFriendlyName":"/Users/tedinger/Parallels/ITDATA-vm2.pvm/ITDATA-vm2-0.hdd",
               "Remote":"0",
               "InterfaceType":"2",
               "StackIndex":"0",
               "DiskType":"1",
               "Size":"262144",
               "SizeOnDisk":"109866",
               "Passthrough":"0",
               "SubType":"0",
               "Splitted":"0",
               "DiskVersion":"2",
               "CompatLevel":"level2",
               "DeviceDescription":"",
               "Password":"",
               "Encrypted":"0",
               "BlockSize":"2048",
               "RuntimeId":"",
               "AutoCompressEnabled":"1",
               "OnlineCompactMode":"1",
               "_id":"0",
               "_dyn_lists":"Partition 0"
            },
            "NetworkAdapter":[
               {
                  "Index":"0",
                  "Enabled":"1",
                  "Connected":"1",
                  "EmulatedType":"2",
                  "SystemName":"",
                  "UserFriendlyName":"Thunderbolt Ethernet Slot  1",
                  "Remote":"0",
                  "AdapterNumber":"2",
                  "AdapterName":"Thunderbolt Ethernet Slot  1",
                  "MAC":"001C42A010DE",
                  "VMNetUuid":"",
                  "HostMAC":"001C4263731D",
                  "HostInterfaceName":"",
                  "Router":"0",
                  "DHCPUseHostMac":"2",
                  "ForceHostMacAddress":"0",
                  "AdapterType":"4",
                  "StaticAddress":"0",
                  "PktFilter":{
                     "PreventPromisc":"1",
                     "PreventMacSpoof":"1",
                     "PreventIpSpoof":"1",
                     "_dyn_lists":""
                  },
                  "LinkRateLimit":{
                     "Enable":"1",
                     "TxBps":"0",
                     "GUITxScale":"1",
                     "RxBps":"0",
                     "GUIRxScale":"1",
                     "TxLossPpm":"0",
                     "RxLossPpm":"0",
                     "TxDelayMs":"0",
                     "RxDelayMs":"0",
                     "_dyn_lists":""
                  },
                  "AutoApply":"0",
                  "ConfigureWithDhcp":"0",
                  "DefaultGateway":"",
                  "ConfigureWithDhcpIPv6":"0",
                  "DefaultGatewayIPv6":"",
                  "NetProfile":{
                     "Type":"0",
                     "Custom":"1",
                     "_dyn_lists":""
                  },
                  "DeviceDescription":"",
                  "_id":"0",
                  "_AdapterType_patch":"1",
                  "_dyn_lists":"NetAddress DnsIPAddress SearchDomain"
               },
               {
                  "Index":"1",
                  "Enabled":"1",
                  "Connected":"1",
                  "EmulatedType":"1",
                  "SystemName":"",
                  "UserFriendlyName":"Shared Network (Recommended)",
                  "Remote":"0",
                  "AdapterNumber":"-1",
                  "AdapterName":"Shared Network",
                  "MAC":"001C42E4755A",
                  "VMNetUuid":"",
                  "HostMAC":"001C4274C558",
                  "HostInterfaceName":"",
                  "Router":"0",
                  "DHCPUseHostMac":"2",
                  "ForceHostMacAddress":"0",
                  "AdapterType":"4",
                  "StaticAddress":"0",
                  "PktFilter":{
                     "PreventPromisc":"1",
                     "PreventMacSpoof":"1",
                     "PreventIpSpoof":"1",
                     "_dyn_lists":""
                  },
                  "LinkRateLimit":{
                     "Enable":"1",
                     "TxBps":"0",
                     "GUITxScale":"1",
                     "RxBps":"0",
                     "GUIRxScale":"1",
                     "TxLossPpm":"0",
                     "RxLossPpm":"0",
                     "TxDelayMs":"0",
                     "RxDelayMs":"0",
                     "_dyn_lists":""
                  },
                  "AutoApply":"0",
                  "ConfigureWithDhcp":"0",
                  "DefaultGateway":"",
                  "ConfigureWithDhcpIPv6":"0",
                  "DefaultGatewayIPv6":"",
                  "NetProfile":{
                     "Type":"0",
                     "Custom":"1",
                     "_dyn_lists":""
                  },
                  "DeviceDescription":"",
                  "_id":"4",
                  "_AdapterType_patch":"1",
                  "_dyn_lists":"NetAddress DnsIPAddress SearchDomain"
               }
            ],
            "Sound":{
               "Enabled":"1",
               "Connected":"1",
               "EmulatedType":"0",
               "AdvancedType":"2",
               "HDAPatchApplied":"1",
               "SystemName":"",
               "UserFriendlyName":"",
               "Remote":"0",
               "VolumeSync":"1",
               "Output":"Default",
               "Mixer":"Default",
               "Channel":"0",
               "AEC":"0",
               "SoundInputs":{
                  "Sound":{
                     "Enabled":"0",
                     "Connected":"1",
                     "EmulatedType":"0",
                     "AdvancedType":"0",
                     "HDAPatchApplied":"0",
                     "SystemName":"0|1|7a4342575153757fe359779b26641a7d8553d9a3",
                     "UserFriendlyName":"Default",
                     "Remote":"0",
                     "VolumeSync":"1",
                     "Output":"Default",
                     "Mixer":"Default",
                     "Channel":"0",
                     "AEC":"0",
                     "SoundInputs":{
                        "_dyn_lists":"Sound 0"
                     },
                     "SoundOutputs":{
                        "_dyn_lists":"Sound 0"
                     },
                     "DeviceDescription":"",
                     "_Mixer_patch":"1",
                     "_id":"0",
                     "_AdvancedType_patch":"",
                     "_Output_patch":"1",
                     "_dyn_lists":""
                  },
                  "_dyn_lists":"Sound 1"
               },
               "SoundOutputs":{
                  "Sound":{
                     "Enabled":"0",
                     "Connected":"1",
                     "EmulatedType":"0",
                     "AdvancedType":"0",
                     "HDAPatchApplied":"0",
                     "SystemName":"1|1|dda47b44f2614b04cbaa649ea54213d4e451709e",
                     "UserFriendlyName":"Default",
                     "Remote":"0",
                     "VolumeSync":"1",
                     "Output":"Default",
                     "Mixer":"Default",
                     "Channel":"0",
                     "AEC":"0",
                     "SoundInputs":{
                        "_dyn_lists":"Sound 0"
                     },
                     "SoundOutputs":{
                        "_dyn_lists":"Sound 0"
                     },
                     "DeviceDescription":"",
                     "_Mixer_patch":"1",
                     "_id":"0",
                     "_AdvancedType_patch":"",
                     "_Output_patch":"1",
                     "_dyn_lists":""
                  },
                  "_dyn_lists":"Sound 1"
               },
               "DeviceDescription":"",
               "_Mixer_patch":"1",
               "_id":"0",
               "_AdvancedType_patch":"101",
               "_Output_patch":"1",
               "_dyn_lists":""
            },
            "USB":{
               "Enabled":"1",
               "Connected":"1",
               "EmulatedType":"0",
               "SystemName":"",
               "UserFriendlyName":"",
               "Remote":"0",
               "AutoConnect":"1",
               "ConnectReason":"0",
               "DeviceDescription":"",
               "UsbType":"0",
               "_id":"0",
               "_dyn_lists":""
            },
            "UsbConnectHistory":{
               "USBPort":[
                  {
                     "Location":"01000000",
                     "SystemName":"VIRTUAL@MOUSE@|203a|fffc|full|--|PW3.0",
                     "Timestamp":"1597689369248",
                     "_id":"0",
                     "_dyn_lists":""
                  },
                  {
                     "Location":"02000000",
                     "SystemName":"VIRTUAL@UVC@|203a|fff9|high|--|0x8020000005ac8514",
                     "Timestamp":"1597689369249",
                     "_id":"1",
                     "_dyn_lists":""
                  },
                  {
                     "Location":"02010000",
                     "SystemName":"VIRTUAL@PRINTER@|203a|fffa|full|--|TAG21d87aca0@Parallels Virtual PDF Printer",
                     "Timestamp":"1597514328025",
                     "_id":"2",
                     "_dyn_lists":""
                  },
                  {
                     "Location":"02020000",
                     "SystemName":"VIRTUAL@PRINTER@|203a|fffa|full|--|TAG31d87aca0@Parallels Virtual PDF Printer",
                     "Timestamp":"1597689378243",
                     "_id":"3",
                     "_dyn_lists":""
                  },
                  {
                     "Location":"03000000",
                     "SystemName":"VIRTUAL@UVC@|203a|fff9|high|--|0x8020000005ac8514",
                     "Timestamp":"1597689372795",
                     "_id":"4",
                     "_dyn_lists":""
                  }
               ],
               "_dyn_lists":"USBPort 5"
            },
            "BTConnectHistory":{
               "_dyn_lists":"BTDevConnect 0"
            },
            "TpmChip":{
               "Type":"0",
               "Policy":"3",
               "_dyn_lists":""
            },
            "_dyn_lists":"Fdd 0 CdRom 1 Hdd 1 Serial 0 Parallel 0 Printer 0 NetworkAdapter 5 Sound 1 USB 1 PciVideoAdapter 0 GenericDevice 0 GenericPciDevice 0 GenericScsiDevice 0 GenericNvmeDevice 0"
         },
         "InstalledSoftware":"0",
         "ExternalConfigInfo":{
            "Type":"0",
            "ConfigPath":"",
            "CheckSum":"",
            "_dyn_lists":""
         },
         "_id":"-1",
         "_dyn_lists":"VirtualAppliance 0"
      }
   }
}

vmObj = x.CurrentVm.ParallelsVirtualMachine.Hardware.Memory.RAM

ddd = vmObj.Hardware.Memory.
